# Generated by Django 3.2.7 on 2021-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
