# Generated by Django 3.2.7 on 2021-11-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('add', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
