# Generated by Django 3.2.7 on 2021-11-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comingmovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comingmovie',
            },
        ),
    ]
